name: Release

on:
  push:
    branches: ["master", "test", "butterfly"]
  pull_request:
    branches: ["master", "test", "butterfly"]
  workflow_dispatch:
    inputs:
      build_type:
        description: "Choose build type (debug or release)"
        required: true
        default: "release"

env:
  BUILD: ${{ github.run_number }}

jobs:
  Windows:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        BUILD_TYPE: ["debug", "release"]
        DISCORD_INTEGRATION: ["using discord", "not using discord"]
    env:
      dev: ${{ matrix.BUILD_TYPE == 'debug' && '_dev' || '' }}
      cmd: ${{ matrix.BUILD_TYPE == 'release' && '--release-build --strip-binary' || '' }}
      discord: ${{ matrix.DISCORD_INTEGRATION == 'using discord' && '--with-discord' || '' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y binutils-mingw-w64-i686 gcc-mingw-w64-i686 g++-mingw-w64-i686 yasm python3-pip
          pip3 install meson ninja

      - name: Env setup
        run: mkdir -p ciout

      - name: Configure
        env:
          CC: i686-w64-mingw32-gcc
          CXX: i686-w64-mingw32-g++
          LD: i686-w64-mingw32-ld
          AR: i686-w64-mingw32-ar
          RANLIB: i686-w64-mingw32-ranlib
          AS: i686-w64-mingw32-as
        run: ./configure --cross=i686-w64-mingw32 ${{env.cmd}} ${{env.discord}}

      - name: Build
        run: |
          make clean
          make -j$(nproc)
          mv DerivedData/MinGW-i686/onscripter-ru.exe ciout
          cp -r Resources/Windows/dlls ciout/dlls
          cd ciout
          zip -qry onscripter-ru_win_r${BUILD}${{env.dev}}${{env.discord}}.zip onscripter-ru.exe dlls

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-build-${{ matrix.BUILD_TYPE }}-${{ strategy.job-index }}
          path: ciout/*.zip

  Linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        BUILD_TYPE: ["debug", "release"]
    env:
      dev: ${{ matrix.BUILD_TYPE == 'debug' && '_dev' || '' }}
      cmd: ${{ matrix.BUILD_TYPE == 'release' && '--release-build --strip-binary' || '' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y yasm libreadline-dev libasound-dev libgl1-mesa-dev libegl1-mesa-dev libxrandr-dev python3-pip
          pip3 install meson ninja

      - name: Env setup
        run: mkdir -p ciout

      - name: Configure
        run: ./configure ${{env.cmd}}

      - name: Build
        run: |
          make clean
          make -j$(nproc)
          mv DerivedData/Posix-x86_64/onscripter-ru ciout
          cd ciout
          zip -qry onscripter-ru_linux64_r${BUILD}${{env.dev}}.zip onscripter-ru
          
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-${{ matrix.BUILD_TYPE }}
          path: ciout/*.zip

  macOS:
    runs-on: macos-11
    strategy:
      matrix:
        BUILD_TYPE: ["Debug", "Release"]
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
      dev: ${{ matrix.BUILD_TYPE == 'Debug' && '_dbg' || '' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install deps
        run: brew install yasm meson ninja

      - name: Env setup
        run: mkdir -p ciout

      - name: Build
        run: |
          xcodebuild ARCHS=x86_64 ONLY_ACTIVE_ARCH=NO -target onscripter-ru-osx -configuration ${{ matrix.BUILD_TYPE }}
          mv build/${{ matrix.BUILD_TYPE }}/onscripter-ru-osx.app ciout
          cd ciout
          zip -qry onscripter-ru_osx_r${BUILD}${{ env.dev }}.zip onscripter-ru-osx.app
          
      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build-${{ matrix.BUILD_TYPE }}
          path: ciout/*.zip

  Publish_Release:
    needs: [Windows, Linux, macOS]
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' 
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release_assets
          merge-multiple: true

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: z${{ github.run_number }}
          name: ONScripter-ru r${{ github.run_number }}
          artifacts: "release_assets/*.zip"
          # Imposta come 'Latest' solo se il push è sul branch master
          makeLatest: ${{ github.ref == 'refs/heads/master' }} 
          # Imposta come Pre-release se il push è sul branch test O sul branch butterfly
          prerelease: ${{ github.ref == 'refs/heads/test' || github.ref == 'refs/heads/butterfly' }}
